### ISSUE TITLE
Crashes on start (fresh install 5.0)

### ISSUE THREAD

**Issue by c33s** [awaescher/RepoZ#83] opened 2019-08-09 18:46 UTC
os: win7x64

from windows event log:
```
Faulting application name: RepoZ.exe, version: 5.0.0.0, time stamp: <redacted>
Faulting module name: KERNELBASE.dll, version: 6.1.<redacted>, time stamp: <redacted>
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0xb0c
Faulting application start time:<redacted>
Faulting application path: C:\Program Files\RepoZ\RepoZ.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: <redacted>
```

is there a specific dotnet lib or c lib i have to install to make it work?

edit:
looks like my dotnet version is wrong/too old?
```
Application: RepoZ.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at RepoZ.App.Win.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at RepoZ.App.Win.App.Main()
```

**Comment by awaescher** [comment] 2019-08-12 09:00
Hm, `BadImageFormatException` ... Would you please be so kind and check the [.NET Assembly Binding Log (Fusion Log)](https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx).

Luckily I just finished a user friendly tool you can use for this: [Fusion++](https://github.com/awaescher/Fusion/releases).
Just download, run and click on [Record]. Then run RepoZ and reproduce the issue. As soon as RepoZ crashes, you can click on [Stop] to check the log files and report back.

Thanks.

**Comment by c33s** [comment] 2019-08-12 20:29
see https://github.com/awaescher/Fusion/issues/8#issuecomment-520582567

**Comment by awaescher** [comment] 2019-10-02 08:36
I wonder if this is the same issue around System.Net.Http 4.2.0.0 - installing the .NET Framework Runtime v4.7.2 fixes this for a user [over there in Fusion++](https://github.com/awaescher/Fusion/issues/8).

Could you please verify?

**Comment by c33s** [comment] 2019-10-03 16:00
i will give it a try

**Comment by awaescher** [comment] 2019-10-31 18:14
Any info on this @c33s?

**Comment by awaescher** [comment] 2019-11-07 22:04
Closing this now, please feel free to open it again.

**Closed by awaescher** 2019-11-07 22:04 UTC

**Comment by vncastanheira** [comment] 2019-11-17 21:56
Hey, I'm having the exact same problem as the OP.

**Comment by awaescher** [comment] 2019-11-17 22:47
Damn. Can you verify if the framework version v4.7.2 is installed on your machine?

As you can see [in a thread about Fusion++](https://github.com/awaescher/Fusion/issues/8#issuecomment-536756846) there seems to be a lot of confusion about the `HttpClient` these days.

**Comment by vncastanheira** [comment] 2019-11-17 22:53
@awaescher Yes, it's installed on my machine.
