### ISSUE TITLE
Crash after fresh install

### ISSUE THREAD

**Issue by rafpran** [awaescher/RepoZ#75] opened 2019-04-23 07:18 UTC
My system: Win10, up to date
Stack:

`Application: RepoZ.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at TinySoup.WebSoupClient+<CallWebServiceAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[TinySoup.WebSoupClient+<CallWebServiceAsync>d__8, RepoZ, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null]](<CallWebServiceAsync>d__8 ByRef)
   at TinySoup.WebSoupClient.CallWebServiceAsync(System.String, System.String)
   at TinySoup.WebSoupClient.PutAsync(System.String)
   at TinySoup.WebSoupClient+<CheckForUpdatesAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at RepoZ.App.Win.App+<CheckForUpdatesAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at RepoZ.App.Win.App+<<OnStartup>b__8_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

`

`Faulting application name: RepoZ.exe, version: 5.0.0.0, time stamp: 0x5ca5de56
Faulting module name: KERNELBASE.dll, version: 10.0.16299.1004, time stamp: 0x690aa820
Exception code: 0xe0434352
Fault offset: 0x00104622
Faulting process id: 0x1148
Faulting application start time: 0x01d4f9a420854b19
Faulting application path: c:\Program Files\RepoZ\RepoZ.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: e04ca0f4-5be1-41ee-b5c5-e8d951bf52fa
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by awaescher** [comment] 2019-05-23 14:58
Would you mind to help me out with this?

I suspect this code: [`await client.GetStreamAsync(uri)`](
https://github.com/awaescher/RepoZ/blob/bf2c9bf33c5067e40c3283ce76c3bbc8422e23c8/RepoZ.App.Win/TinySoup.cs#L102) to cause the issue. However, I cannot see which file the runtime wants to load just by reading your callstack.

Would you please be so kind and check this out for me? This can be done by activating the [.NET Assembly Binding Log (Fusion Log)](https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx).

Luckily I just finished a user friendly tool you can use for this: [Fusion++](https://github.com/awaescher/Fusion/releases).
Just download, run and click on [Record]. Then run RepoZ and reproduce the issue. As soon as RepoZ crashes, you can click on [Stop] to check the log files and report back.

Thanks.

**Comment by awaescher** [comment] 2019-07-26 22:07
Okay, I did not manage to make RepoZ crash. Since I got no further feedback, I'll close this now.

**Closed by awaescher** 2019-07-26 22:07 UTC
Labels: bug
